### ISSUE TITLE
🎉500 Stars🎉

### ISSUE THREAD

**Issue by Mouse0w0** [Mouse0w0/MinecraftDeveloperGuide#10]

**Comment by Fs791010** [comment]
OK



在 2021-06-15 18:39:51，"Mouse" ***@***.***> 写道：

Closed #10.

**Comment by mouse0w0** [comment]
900 Stars
![](https://user-images.githubusercontent.com/13087252/146670855-6e5e1f62-14cd-45a2-bb9a-941100e5cb46.png)
