### ISSUE TITLE
添加“启动器”开发相关资料/文档/教程/类库

### ISSUE THREAD

**Issue by Mouse0w0** [Mouse0w0/MinecraftDeveloperGuide#12]
欢迎各位开发者在本Issue推荐/自荐与“Minecraft启动器”相关的资料/文档/教程/类库。

**Comment by xtexChooser** [comment]
HMCLCore(可用jitpack构建)
https://minecraft-zh.gamepedia.com/%E6%95%99%E7%A8%8B/%E7%BC%96%E5%86%99%E5%90%AF%E5%8A%A8%E5%99%A8

wiki.vg
