### ISSUE TITLE
征集“着色器包”开发相关资料/文档/教程/类库

### ISSUE THREAD

**Issue by mouse0w0** [mouse0w0/MinecraftDeveloperGuide#13]
欢迎各位开发者在本Issue推荐/自荐与“Minecraft着色器包”相关的资料/文档/教程/类库。

**Comment by maxmium12** [comment]
一篇非常详细的opengl教程
[https://learnopengl-cn.github.io/](url)

**Comment by ksgfk** [comment]
应该是最好的入门教程了，学完第9课和配套练习，再看其他教程会容易些
https://www.bilibili.com/video/BV1X7411F744

**Comment by alex3236** [comment]
Optifine 官方文档翻译
https://mcbbs.net/thread-896135-1-1.html

**Comment by HamiltonHuaji** [comment]
自荐 [如何编写OptiFine光影包](https://hamiltonhuaji.github.io/tags/Shaderpack/)
近期爆肝更新中

**Comment by SugarMGP** [comment]
我的世界图形学社区文档
https://mgcd.hypercol.com/

**Comment by 3093FengMing** [comment]
saada2006的示例代码及教程：
代码：https://github.com/saada2006/MinecraftShaderProgramming
教程网站：https://saada2006.github.io/minecraft-shader-tutorials

GamesWithGabe的示例代码及教程：
youtube合辑：https://youtube.com/playlist?list=PLtrSb4XxIVbodGYZZVzC1PAZfwckrXp_X（只有4集）
github教程&代码（含文字）：https://github.com/codingminecraft/MinecraftCloneForYoutube

TheCman5015PLPro的教程（7-8年前）：
youtube合辑（SEUS V11）：https://youtube.com/playlist?list=PLLbNWy4Fb15ateKUnhosCcqkb1qSHW1f7
youtube合辑（KUDA）：https://youtube.com/playlist?list=PLLbNWy4Fb15btVjg3Iuw1Irkpll4bTYJK
youtube合辑（SEUS V10.2 ULTRA）：https://youtube.com/playlist?list=PLLbNWy4Fb15Y-b0-pELRQxQObjnUl1DjI

有关GLSL的教程（不是针对Minecraft）：
https://thebookofshaders.com
OpenGL官方pdf：https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.1.20.pdf

光影交流的DC：https://discordapp.com/invite/F4BtNAc

**Comment by mouse0w0** [comment]
@3093FengMing 感谢您对我的世界开发者中文指南的贡献。

仅采纳`saada2006的示例代码及教程`、`OpenGL官方pdf`和`光影交流的DC`，其余未采纳的理由如下：
- `GamesWithGabe的示例代码及教程`：并非光影包开发相关内容，而是开发一个类似我的世界的游戏。
- `TheCman5015PLPro的教程`：并非光影包开发相关内容，而是修改某个指定的光影包。
- `有关GLSL的教程（不是针对Minecraft）`：内容不完整。

**Comment by 3093FengMing** [comment]
我的世界图形学社区文档已迁移至https://docs.minegraph.cn/home
