### ISSUE TITLE
添加“镜像源”相关资料/文档/教程

### ISSUE THREAD

**Issue by Mouse0w0** [Mouse0w0/MinecraftDeveloperGuide#16]
欢迎各位开发者在本Issue推荐/自荐与“镜像源”使用相关的资料/文档/教程。

**Comment by yaesey** [comment]
我直接吹爆lss233的源！真的屡次在风雨飘摇的网络环境配置中帮大忙了！
https://www.mcbbs.net/thread-800729-1-1.html

**Comment by yaesey** [comment]
等等，哦，不好意思，我才发现在原代码库里面已经有这个链接了😂
