### ISSUE TITLE
添加“Java基础/扩展阅读”相关资料/文档/教程/书籍

### ISSUE THREAD

**Issue by Mouse0w0** [Mouse0w0/MinecraftDeveloperGuide#17]
欢迎各位开发者在本Issue推荐/自荐与“Java基础/扩展阅读”相关的资料/文档/教程/书籍。

**2021/2/19更新**：
本栏目希望添加一些能够提高Java初学者能力的书籍、资料、文档、教程。

**Comment by yaesey** [comment]
关于Java基础的话，imooc上面有三个免费课程可以作为快速扫盲和应急使用。
课程里面有很多编程实践场和一些练手小项目
入门：https://m.imooc.com/learn/85
面向对象：https://m.imooc.com/learn/124
异常/字符串/Set、List等常用数据结构：https://m.imooc.com/learn/110

**Comment by yaesey** [comment]
gradle可以参考immoc的免费教程https://m.imooc.com/learn/833

但最好最权威最新的还是gradle文档（）
https://gradle.org/install/或https://docs.gradle.org/current/userguide/userguide.html

**Comment by tangguoQAQ** [comment]
[https://www.learnjavaonline.org/](https://www.learnjavaonline.org/)
我是nino

**Comment by tangguoQAQ** [comment]
上面是英文的，这有个Java速成（？
[https://oi-wiki.org/lang/java/](https://oi-wiki.org/lang/java/)

**Comment by Mouse0w0** [comment]
> https://www.learnjavaonline.org/
> 我是nino

> 上面是英文的，这有个Java速成（？
> https://oi-wiki.org/lang/java/

两者内容还是略显单薄一些了。
