### ISSUE TITLE
添加“游戏开发基础/扩展阅读”相关资料/文档/教程/书籍

### ISSUE THREAD

**Issue by ChloePrime** [Mouse0w0/MinecraftDeveloperGuide#18]
欢迎各位开发者在本Issue推荐/自荐与“游戏开发基础/扩展阅读”相关的资料/文档/教程/书籍。

本栏目希望添加一些能够提高游戏开发能力的书籍、资料、文档、教程，
例如计算机图形学，3d数学，技能设计，数值/玩法/流程策划等。

如果你想制作一个好看，好玩，又平衡的高质量mod的话，这些知识是必不可少的~

**Comment by yaesey** [comment]
https://github.com/Angry-Pixel/The-Betweenlands
交错次元源码）
维度、渲染、特效等等参考
