### ISSUE TITLE
Forge社区wiki

### ISSUE THREAD

**Issue by Snownee** [Mouse0w0/MinecraftDeveloperGuide#20]
**名称：**
Forge社区wiki

**URL链接（请尽量提供多个渠道的链接）：**
https://forge.gemwire.uk/

**分类：**
Forge模组开发

**适用的我的世界版本：**
Java版 1.16+

**推荐词：**
仅供参考

**Comment by Mouse0w0** [comment]
已采纳，感谢贡献~❤
