### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by Snownee** [Mouse0w0/MinecraftDeveloperGuide#22]
- 【1.8】日本的模组开发百科
- 【全版本】雪崩式的灾难：严重滞后的世界生成
- 【全版本】简单网络通信包装类(SimpleNetworkWrapper)
- 【1.11.2】基于代码的简单方块/物品贴图渲染
- 【1.10.2+】1.10.2以上的方块与物品渲染

**Comment by Mouse0w0** [comment]
需要解锁卡才能查看的帖子将尽量使用备用连接替代，如无备用链接则仍保持原样

**Comment by Mouse0w0** [comment]
已采纳，感谢提交
