### ISSUE TITLE
Forge安装和常见错误

### ISSUE THREAD

**Issue by GongXiaoBei77** [mouse0w0/MinecraftDeveloperGuide#29]
**名称：**
Forge安装到导出详细入门教程|各种报错解决方法

**URL链接（请尽量提供多个渠道的链接）：**
[[IntelliJ IDEA|多版本通用]Forge安装到导出详细入门教程|各种报错解决方法](https://www.mcbbs.net/thread-1193768-1-3.html)

**分类：**
Forge模组开发

**适用的我的世界版本：**
多版本通用

**推荐词：**
Forge安装 |  常见报错

**Comment by mouse0w0** [comment]
已采纳，感谢对我的世界开发者中文指南的贡献。
