### ISSUE TITLE
ForgeDocs

### ISSUE THREAD

**Issue by GongXiaoBei77** [mouse0w0/MinecraftDeveloperGuide#30]
**名称：**
Forge Java Docs 多版本

**URL链接（请尽量提供多个渠道的链接）：**
[Forge Java Docs 1.12-1.18](https://github.com/Nekoyue/ForgeJavaDocs-NG)
[Forge Java Docs 1.7.10-1.11.2](https://skmedix.github.io/ForgeJavaDocs/)

**分类：**
Forge模组开发

**适用的我的世界版本：**
Java版 1.7.10-.1.18

**推荐词：**
Doc文档/查阅开发

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的支持。
