### ISSUE TITLE
Minecraft通信协议

### ISSUE THREAD

**Issue by GongXiaoBei77** [mouse0w0/MinecraftDeveloperGuide#31]
**名称：**
教你如何从外部 Ping 通服务器

**URL链接（请尽量提供多个渠道的链接）：**
[教你如何从外部 Ping 通服务器](https://www.mcbbs.net/forum.php?mod=viewthread&tid=1280861)

**分类：**
Bukkit/Spigot插件开发

**适用的我的世界版本：**
JAVA通用

**推荐词：**
插件开发教程/Bukkit插件开发教程/高质量插件系列/协议

**Comment by mouse0w0** [comment]
已采纳。由于教程是基于Socket的网络通信程序，不属于`Bukkit/Spigot插件开发`分类，已被添加到`常用网站与资源>其他开发资料`分类下。感谢您对我的世界开发者中文指南的支持。
