### ISSUE TITLE
添加 Minecraft Forge 构建开发环境网络代理配置教程

### ISSUE THREAD

**Issue by ZekerZhayard** [mouse0w0/MinecraftDeveloperGuide#34]
### 名称

Minecraft Forge 构建开发环境网络代理配置教程

### URL链接

https://zekerzhayard.gitbook.io/minecraft-forge-gou-jian-kai-fa-huan-jing-wang-luo-dai-li-pei-zhi-jiao-cheng/

### 分类

常用网站和资源 -- 其他开发资源

### 适用的我的世界版本

Minecraft Forge 通用

### 推荐词

还真没有

**Comment by mouse0w0** [comment]
已添加在`Forge 模组开发 > MDK（Minecraft开发工具包）`条目下。
