### ISSUE TITLE
征集“基岩版服务端”开发相关资料/文档/教程/类库/软件

### ISSUE THREAD

**Issue by mouse0w0** [mouse0w0/MinecraftDeveloperGuide#35]

**Comment by xtexChooser** [comment]
BEDEV Wiki: https://wiki.bedev.cn/page/Minecraft%E5%9F%BA%E5%B2%A9%E7%89%88%E5%BC%80%E5%8F%91Wiki

**Comment by xtexChooser** [comment]
bedrock.dev: https://bedrock.dev/zh

Bedrock Edition Creator Documentation by Microsoft: https://docs.microsoft.com/en-us/minecraft/creator/

**Comment by xtexChooser** [comment]
bedrock.dev wiki: https://wiki.bedrock.dev/

**Comment by mouse0w0** [comment]
@killcerr 已采纳，将会等待推出稳定版后修改，感谢您对我的世界开发者中文指南的贡献。

**Comment by killcerr** [comment]
https://zh.minecraft.wiki/w/%E5%9F%BA%E5%B2%A9%E7%89%88%E4%B8%93%E7%94%A8%E6%9C%8D%E5%8A%A1%E5%99%A8
添加mcwiki的链接

**Comment by mouse0w0** [comment]
> https://zh.minecraft.wiki/w/%E5%9F%BA%E5%B2%A9%E7%89%88%E4%B8%93%E7%94%A8%E6%9C%8D%E5%8A%A1%E5%99%A8
内容过于简单，不予采纳。
