### ISSUE TITLE
Fabric开发教程增加示例模组

### ISSUE THREAD

**Issue by RawDiamondMC** [mouse0w0/MinecraftDeveloperGuide#39]
### 名称

Fabric示例模组

### URL链接

https://fabricmc.net/develop/template/
https://github.com/FabricMC/fabric-example-mod

### 分类

Fabric模组开发

### 适用的我的世界版本

任何Fabric支持Release版本

### 推荐词

提供了Fabric模组模板

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。

**Comment by PlainsVillager** [comment]
这个好
