### ISSUE TITLE
自荐一个 HoloJaneway

### ISSUE THREAD

**Issue by USS-Shenzhou** [mouse0w0/MinecraftDeveloperGuide#41]
### 名称

HoloJaneway

### URL链接

https://holojaneway.uss-shenzhou.cn/holojaneway

### 分类

Forge模组开发

### 适用的我的世界版本

Java 1.18.2+

### 推荐词

是自己在尝试写的教程~
待完成的部分还有点多，不过在慢慢推进了

**Comment by mouse0w0** [comment]
已采纳
