### ISSUE TITLE
Minecraft启动器制作教程电子书

### ISSUE THREAD

**Issue by rechalow** [mouse0w0/MinecraftDeveloperGuide#43]
### 名称

Lets Make A Minecraft Launcher!!

### URL链接

https://rechalow.github.io/lmaml

### 分类

Java版启动器开发

### 适用的我的世界版本

全版本

### 推荐词

非常完善的，无需任何类库即可制作出一款Minecraft启动器！
本教程开发使用的语言为Delphi/Object Pascal

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南和我的世界中文社区的贡献。

个人建议删除较为主观的《编程语言的选择》相关内容，期待您完善登录部分的内容。
