### ISSUE TITLE
EnchantmentAPI 教程过时

### ISSUE THREAD

**Issue by William-Shi233** [mouse0w0/MinecraftDeveloperGuide#44]
https://www.mcbbs.net/forum.php?mod=viewthread&tid=782859

该教程中内容全部以截图形式呈现，而作者所使用的图床已经不再运营。

另外，自 SpigotMC 社区中的反馈（[https://www.spigotmc.org/resources/enchantmentapi.48372/reviews](https://www.spigotmc.org/resources/enchantmentapi.48372/reviews)）可知，这个插件仅能支持 1.12 版本，在 1.13 版本报错颇多，且五年前就停更了。

另外，[《使用BlockData API来操作Sign》](http://www.mcbbs.net/thread-860856-1-1.html) 这篇教程不知道是处于审核中状态还是已被删除。

另外，[《编辑，获取并使用木牌》](http://www.mcbbs.net/thread-697373-1-1.html) 这篇教程出现了严重的 [code] 内代码丢失问题，无法阅读，也没有提供原文链接。

**Comment by mouse0w0** [comment]
感谢您对我的世界开发者中文指南的贡献，已经移除失效的[《使用BlockData API来操作Sign》](http://www.mcbbs.net/thread-860856-1-1.html)，已为[《编辑，获取并使用木牌》](http://www.mcbbs.net/thread-697373-1-1.html)和[《Enchantment API 教程》](http://www.mcbbs.net/thread-782859-1-1.html)添加删除线并移动到最后。
