### ISSUE TITLE
推荐一个Forge mod 教程

### ISSUE THREAD

**Issue by Ginsway** [mouse0w0/MinecraftDeveloperGuide#45]
### 名称

 Minecraft 1.12.2 Forge Mod 开发教程-Sphinx

### URL链接

https://mc1122modtutorialdocs-sphinx.readthedocs.io/zh_CN/latest/

### 分类

Forge模组开发

### 适用的我的世界版本

1.12.2

**Comment by rechalow** [comment]
这边建议再完善一下再发布呢！
因为这篇教程看着似比harbinger、土球的书讲解的要少很多。

**Comment by mouse0w0** [comment]
该教程内容过少且已归档，不予采纳。
