### ISSUE TITLE
添加新Forge代码示例

### ISSUE THREAD

**Issue by 3093FengMing** [mouse0w0/MinecraftDeveloperGuide#46]
### 名称

【1.18.1+】Kaupenjoe的模组示例代码

### URL链接

https://github.com/Tutorials-By-Kaupenjoe/Forge-Tutorial-1.18.1

### 分类

Forge模组开发

### 适用的我的世界版本

Java 1.18.1+

### 推荐词

一共70个分支，每个分支都可以单独作为mod，很全面，涵盖最基本的方块、物品、游戏修改、模型、datagen，以及升级版本的示例

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
