### ISSUE TITLE
推荐一个MCP

### ISSUE THREAD

**Issue by 071205080112** [mouse0w0/MinecraftDeveloperGuide#47]
### 名称

RetroMCP-Java

### URL链接

[RetroMCP Wiki](https://github.com/MCPHackers/RetroMCP-Java/wiki) 

### 分类

Mod Coder Pack

### 适用的我的世界版本

1.5.2 - rd-132211 中的部分版本

### 推荐词

A rewrite of MCP to provide support for many versions of Minecraft which were never supported by original MCP
重写了MCP，以支持许多从未被原MCP支持的版本的Minecraft

**Comment by 071205080112** [comment]
补充一下储存库的链接：[RetroMCP-Java](https://github.com/MCPHackers/RetroMCP-Java)

**Comment by 071205080112** [comment]
这是支持的版本的信息：[MAPPINGS_JSON](https://mcphackers.org/versionsV2/versions.json)

**Comment by mouse0w0** [comment]
目前支持的版本过于古老，暂时不予采纳，待原作者更新后再添加，感谢您对我的世界开发者中文指南的贡献。

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
