### ISSUE TITLE
我的世界视频教程，包含了1.16.5的Forge教程，1.19.2的Forge，1.20.1的Fabric 和以及之后会更新的1.20.1的Forge教程

### ISSUE THREAD

**Issue by Flandre923** [mouse0w0/MinecraftDeveloperGuide#49]
### 名称

视频教程包含了Forge和Fabric其中有包含了HUD,GUI,方块实体，实体，世界生成等等内容。

### URL链接

个人B站视频空间：https://space.bilibili.com/4550069
1.16.5 Forge教程：https://www.bilibili.com/video/BV1WM4y1K7D5
1.20.1 Fabric教程：https://www.bilibili.com/video/BV1Kj411f7Zt
1.１９.２ Froge教程：https://www.bilibili.com/video/BV1mV411u73D

### 分类

Forge模组开发，Fabric模组开发

### 适用的我的世界版本

1.16.5；1.19.2；1.20.1；

### 推荐词

这个是个人的录制的视频教程。包含了1.16.5的Forge教程。1.19.2的Froge教程。1.20.1的Froge教程。其中的内容包含了添加基础的方块，物品，添加具有功能的方块，物品，以及添加合成表和掉落物表，数据生成DataGen，以及自定义物品，方块模型，添加方块实体，流体，实体，热键，世界生成，以及之后会更新维度生成，给MOD添加配置类。
其中的部分代码内容和贴图的来自：Modding by Kaupenjoe 
在他的内容的基础上，对视频进行了重录，中文讲解，添加了一些他没有讲到的内容，例如数据生成，维度，配置Config等等。
本视频目前还在更新中，内容基本录制好了，会在之后逐渐上传。

**Comment by mouse0w0** [comment]
虽然在本指南中已有多个国外的视频教程，但是否采纳中文的视频教程仍存在较大争议，特在此issue进行讨论。

**视频教程的优点：**
1. 线性式的教学能够让学习者不易跟丢。
2. 更清楚的看到教程录制者的操作。
3. 易于录制，只需录制操作并解说即可。

**视频教程的缺点：**
1. 线性式的教学使得学习者不易查询。
2. 视频教程录制或发布后不易修改。
3. 不易编辑，录制的视频中的无效内容难以去除。

本issue中所推荐的视频教程，我个人认为存在一些概念解释不清楚的问题，并且对其修改的工作量是不小的。综上所述，对是否采纳此issue本人暂持保留意见，欢迎各位讨论。

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。

**Comment by luiqn2007** [comment]
个人更倾向于文档形式的教程。或许可以相融合？在文档中插入视频片段演示各资源所在位置及实现效果
