### ISSUE TITLE
两三条小建议

### ISSUE THREAD

**Issue by 3TUSK** [Mouse0w0/MinecraftDeveloperGuide#5]
- TheGreyGhost 的 MinecraftByExample 已经更新 1.14 和 1.15 分支了，可以考虑更新版本标记。
   - TheGreyGhost 的博客和 TA 的示例代码可搭配阅读，也可以推荐：https://greyminecraftcoder.blogspot.com/ 但它是在 BlogSpot 上的。
 - 有人推荐 TurtyWurty 的视频系列（1.15.2/1.12.2）https://www.youtube.com/channel/UCicAXLV4w2X6bn2EuM4To4w

**Comment by Mouse0w0** [comment]
已采纳，感谢你的建议
