### ISSUE TITLE
添加【Minecraft实体运动研究与应用】

### ISSUE THREAD

**Issue by SQwatermark** [mouse0w0/MinecraftDeveloperGuide#50]
### 名称

Minecraft实体运动研究与应用

### URL链接

http://lovexyn0827.space/mcdocs/docs/Minecraft%E5%AE%9E%E4%BD%93%E8%BF%90%E5%8A%A8%E7%A0%94%E7%A9%B6%E4%B8%8E%E5%BA%94%E7%94%A8/Minecraft%E5%AE%9E%E4%BD%93%E8%BF%90%E5%8A%A8%E7%9B%B8%E5%85%B3%E7%A0%94%E7%A9%B6%E4%B8%8E%E5%BA%94%E7%94%A8

### 分类

通用

### 适用的我的世界版本

Java版

### 推荐词

对原版实体运动相关源码的详细分析，对实体相关开发有很大参考价值

**Comment by mouse0w0** [comment]
已采纳
