### ISSUE TITLE
补档Bukkit/Spigot插件分区的开发教程链接

### ISSUE THREAD

**Issue by LeafletXD** [mouse0w0/MinecraftDeveloperGuide#58]
由于mcbbs的关闭，原指向mcbbs的教程链接丢失，好在我之前有保留过他们的链接

《tdiant的Bukkit插件开发教程》http://bdn.tdiant.net

《补订Rarity的Bukkit插件开发教程》的链接我也有保存，但可惜无法打开，大概作者已经删了
https://plugindiary.pvpin.org

**Comment by mouse0w0** [comment]
补订Rarity的Bukkit插件开发教程的相应Github仓库找不到了，重新使用[Rarity的Bukkit插件开发教程](https://github.com/Andy-K-Sparklight/PluginDiary)的Github仓库作为推荐教程。感谢您对我的世界开发者中文指南的贡献。

**Comment by LeafletXD** [comment]
我想额外问个问题，我能用网页时光机找到mcbbs的那些教程资源，然后我新建仓库，把那些资源放进来再补档能行吗（如果原作者找上门让我删掉那我没辙了XD）

**Comment by mouse0w0** [comment]
应尽量联系原作者将教程上传到Github部署页面。

**Comment by LeafletXD** [comment]
好的
