### ISSUE TITLE
来自一个不知名的 Bukkit 教程的自荐

### ISSUE THREAD

**Issue by ElaBosak233** [Mouse0w0/MinecraftDeveloperGuide#6]
emm，这个 Bukkit / Spigot 的教程没人看，毕竟最近才刚刚发布，发到 mcbbs 上，因为没有审核过，就没有高亮，但是我一直觉得这个教程做的还是不错的

这个是发布的帖子
[https://www.mcbbs.net/thread-1088032-1-1.html](https://www.mcbbs.net/thread-1088032-1-1.html)

这个是教程的内容
[https://valkyrie.elabosak.cn](https://valkyrie.elabosak.cn/#/)

所以，能不能采纳一下呢？如果可以的话， @ElaBosak233，多谢~

**Comment by Mouse0w0** [comment]
👍
