### ISSUE TITLE
我的世界1.20.4 NeoForge20.3 模组开发教程

### ISSUE THREAD

**Issue by Flandre923** [mouse0w0/MinecraftDeveloperGuide#63]
### 名称

我的世界1.20.4 NeoForge20.3 模组开发教程

### URL链接

文字教程(以更新完毕):  https://fuwari-ald.pages.dev/archive/category/Minecraft1_20_4_NeoForge_Tutorial/
视频教程（更新中）：https://www.bilibili.com/video/BV1hv421y7fe/
代码仓库：https://github.com/Flandre923/NeoForgeTutorialmod-Minecraft1.20.4

### 分类

NeoForge模组开发教程

### 适用的我的世界版本

我的世界1.20.4 NeoForge20.3

### 推荐词

有关NeoForge的教程，游戏版本和NeoForge版本都较新，参照了boson的1.16.5教程，对其中空白的内容和没涉及到的内容进行了一定的补充。

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
