### ISSUE TITLE
[重新搭建界面]对于bukkit插件开发RarityEG's Plugin Dev Tutorial 链接失效的重新大家把你

### ISSUE THREAD

**Issue by moran0710** [mouse0w0/MinecraftDeveloperGuide#69]
### 名称

RarityEG's Plugin Dev Tutorial

### URL链接

https://moran0710.github.io/PluginDiary/

### 分类

bukkit插件开发

### 适用的我的世界版本

bukkit 全版本

### 推荐词

因为原先的[Andy-K-Sparklight/PluginDiary](https://github.com/Andy-K-Sparklight/PluginDiary)这个仓库链接炸了，翻仓库里的md文档比较麻烦，于是我将其fork之后搭建在我的Github Pages上了，希望能将修复后的网页挂在原先的推荐链接边上

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
