### ISSUE TITLE
将Java版启动器里的rechalow启动器教程网址修改成xphost008

### ISSUE THREAD

**Issue by xphost008** [mouse0w0/MinecraftDeveloperGuide#75]
### 名称

xphost的启动器教程

### URL链接

https://xphost008.github.io/lmaml

### 分类

java版启动器

### 适用的我的世界版本

全版本

### 推荐词

可以非常好的教会各位基本的启动逻辑和正版登录逻辑！
由于gitee账号已注销，加上电脑拿去维修，导致了我mdbook源码丢失。。不过我正在想办法弥补！

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
