### ISSUE TITLE
星断肃昭的Forge模组开发视频教程

### ISSUE THREAD

**Issue by xingduansuzhao** [mouse0w0/MinecraftDeveloperGuide#78]
### 名称

星断肃昭的Forge模组开发视频教程

### URL链接

抖音：https://www.douyin.com/video/7279377986187431202
B站：https://space.bilibili.com/3537121929332753/channel/collectiondetail?sid=3378523&ctype=0
西瓜视频：https://www.ixigua.com/home/2562275897255528/pseries/?preActiveKey=video&list_entrance=userdetail
![入门教程合集封面重置2](https://github.com/user-attachments/assets/22ec673f-d2d2-4847-a957-2a746bb3efeb)

### 分类

Forge模组开发教程

### 适用的我的世界版本

Java版 1.16.1

### 推荐词

Forge  模组开发  java  模组入门  mod  视频教程  tutorial

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
