### ISSUE TITLE
【1.20】深入浅出高版本渲染系统 —— GuiComponent的消逝与GuiGraphics的新生 被删除

### ISSUE THREAD

**Issue by wangziwenhk** [mouse0w0/MinecraftDeveloperGuide#83]
【1.20】深入浅出高版本渲染系统 —— GuiComponent的消逝与GuiGraphics的新生 被删除,请求撤下

**Comment by mouse0w0** [comment]
原作者已迁移到新链接：https://turou.fun/minecraft/render-tutor/，感谢您对我的世界开发者中文指南的支持。

**Comment by wangziwenhk** [comment]
感谢
