### ISSUE TITLE
关于PowerNukkitX的相关资料

### ISSUE THREAD

**Issue by wuliao697** [mouse0w0/MinecraftDeveloperGuide#91]
### 名称

PowerNukkitX快速入门

### URL链接

https://github.com/wuliao697/PowerNukkitXTutorial

### 分类

基岩版服务端PowerNukkitX插件开发

### 适用的我的世界版本

支持该服务端2.0全版本

### 推荐词

截至今天为止，很遗憾这个社区项目几乎停止跟进新版本特性，主要开发者陆续隐退或转向其他服务端开发。作为纯基岩版第三方服务端，他是这里面原版特性最多最完善的服务端。
我几乎见证了这个服务端生命周期的全部，并亲手写下了这个为时已晚的教程。若有错误，欢迎指出。
这个服务端经历一次全部重构，2.0版本才能适应后续的版本协议的更新。
不过后继有人，仍然在为基岩版相关服务端薪火相传。如原Nukkit开发者的EndStone项目，该项目的主要开发者之一刀哥的Allay项目，和Nukkit-MOT

**Comment by YakumoUUZ** [comment]
邮件已收到，幽幽玄代表八云之家向您问好。

**Comment by mouse0w0** [comment]
已采纳，感谢您对我的世界开发者中文指南的贡献。
